git

diff --git a/users/mabq/config/zsh/aliases b/users/mabq/config/zsh/aliases
--- a/users/mabq/config/zsh/aliases
+++ b/users/mabq/config/zsh/aliases
@@ -1,47 +1,50 @@
 # vim: filetype=sh
 
-# --- File system
+# -- File system
 if command -v eza &>/dev/null; then
-  alias ls='eza -lh --group-directories-first --icons=auto'
-  alias lsa='ls -a'
-  alias lt='eza --tree --level=3 --long --icons --git'
-  alias lta='lt -a'
+	alias ls='eza -lh --group-directories-first --icons=auto'
+	alias lsa='ls -a'
+	alias lt='eza --tree --level=3 --long --icons --git'
+	alias lta='lt -a'
 fi
 
 if command -v zoxide &>/dev/null; then
-  alias cd="zd"
-  zd() {
-    if (($# == 0)); then
-      builtin cd ~ || return
-    elif [[ -d $1 ]]; then
-      builtin cd "$1" || return
-    else
-      if ! z "$@"; then
-        echo "Error: Directory not found"
-        return 1
-      fi
-      printf "\U000F17A9 "
-      pwd
-    fi
-  }
+	alias cd="zd"
+	zd() {
+		if (($# == 0)); then
+			builtin cd ~ || return
+		elif [[ -d $1 ]]; then
+			builtin cd "$1" || return
+		else
+			if ! z "$@"; then
+				echo "Error: Directory not found"
+				return 1
+			fi
+			printf "\U000F17A9 "
+			pwd
+		fi
+	}
 fi
 
 open() (
-  xdg-open "$@" >/dev/null 2>&1 &
+	xdg-open "$@" >/dev/null 2>&1 &
 )
 
-# --- Directories
+# -- Directories
 alias ..='cd ..'
 alias ...='cd ../..'
 alias ....='cd ../../..'
 
-# --- Tools
+# -- Tools
 alias c='opencode'
 # alias cx='printf "\033[2J\033[3J\033[H" && claude --allow-dangerously-skip-permissions'
 alias d='docker'
 # alias r='rails'
 alias t='tmux attach || tmux new -s Work'
 n() { if [ "$" -eq 0 ]; then command nvim .; else command nvim "$@"; fi; }
+
+# -- Git
+alias gl='git log --graph --oneline --all --decorate'
 
 # --- Others
 # alias mkdir='mkdir -p'
@@ -53,7 +56,7 @@ n() { if [ "$" -eq 0 ]; then command nvim .; else command nvim "$@"; fi; }
 # alias mv='mv -iv'
 # alias rm='rm -iv --preserve-root'
 
-# --- Shortcuts/renames
+# -- Shortcuts/renames
 # alias cpuinfo='bat /proc/cpuinfo'
 # alias drivers='lspci -k'
 # alias extip='curl icanhazip.com'
