zsh module restructure

diff --git a/config/zsh/aliases b/config/zsh/aliases
--- a/config/zsh/aliases
+++ b/config/zsh/aliases
@@ -2,32 +2,32 @@
 
 # -- File system
 if command -v eza &>/dev/null; then
-	alias ls='eza -lh --group-directories-first --icons=auto'
-	alias lsa='ls -a'
-	alias lt='eza --tree --level=3 --long --icons --git'
-	alias lta='lt -a'
+  alias ls='eza -lh --group-directories-first --icons=auto'
+  alias lsa='ls -a'
+  alias lt='eza --tree --level=3 --long --icons --git'
+  alias lta='lt -a'
 fi
 
 if command -v zoxide &>/dev/null; then
-	alias cd="zd"
-	zd() {
-		if (($# == 0)); then
-			builtin cd ~ || return
-		elif [[ -d $1 ]]; then
-			builtin cd "$1" || return
-		else
-			if ! z "$@"; then
-				echo "Error: Directory not found"
-				return 1
-			fi
-			printf "\U000F17A9 "
-			pwd
-		fi
-	}
+  alias cd="zd"
+  zd() {
+    if (($# == 0)); then
+      builtin cd ~ || return
+    elif [[ -d $1 ]]; then
+      builtin cd "$1" || return
+    else
+      if ! z "$@"; then
+        echo "Error: Directory not found"
+        return 1
+      fi
+      printf "\U000F17A9 "
+      pwd
+    fi
+  }
 fi
 
 open() (
-	xdg-open "$@" >/dev/null 2>&1 &
+  xdg-open "$@" >/dev/null 2>&1 &
 )
 
 # -- Directories
